apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../

helmCharts:
  - name: helm-charts
    releaseName: housing-api
    valuesFile: ../../base/api/values.yaml
    additionalValuesFiles:
      - api/values-prod.yaml

  - name: helm-charts
    releaseName: housing-ui
    valuesFile: ../../base/ui/values.yaml
    additionalValuesFiles:
      - ui/values-prod.yaml

patches:
  - path: rollout-api-patch.yaml
    target:
      group: argoproj.io     
      kind: Rollout          
      name: housing-api
      
  - path: rollout-ui-patch.yaml
    target:
      group: argoproj.io     
      kind: Rollout         
      name: housing-ui