apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 3.4.0
    helm:
      parameters:
        - name: clusterName
          value: "housing-mlops-eks-cluster" 
        
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: "aws-load-balancer-controller"
          
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::770353436964:role/housing-mlops-aws-lb-controller-role"
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true