apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../

helmCharts:
  - name: helm-charts
    releaseName: housing-api
    additionalValuesFiles:
      - api/values-dev.yaml

  - name: helm-charts
    releaseName: housing-ui
    additionalValuesFiles:
      - ui/values-dev.yaml
