deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
image:
  tag: ee111900fe023469e139fc6909b4ce6352a2d37b
