deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
image:
  tag: 22e66f55865e405a784d3c596cd1b05d95ed4c89
