deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
image:
  tag: 3fc79aa5417087ffe557fe63fb277b47d15a96ef
