apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: housing-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    
    alb.ingress.kubernetes.io/target-type: ip
    
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: housing-api
                port:
                  number: 8000
                  
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: housing-api
                port:
                  number: 8000
                  
          - path: /openapi.json
            pathType: Exact
            backend:
              service:
                name: housing-api
                port:
                  number: 8000

          # --- RULE MẶC ĐỊNH CỦA UI (Streamlit) ---
          - path: /
            pathType: Prefix
            backend:
              service:
                name: housing-ui
                port:
                  number: 8501