deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
env:
  STREAMLIT_SERVER_GATHER_USAGE_STATS: "false"
image:
  tag: 89063fa7bb647ab987e9566e7a4f43afb1872544
