deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
env:
  STREAMLIT_SERVER_GATHER_USAGE_STATS: "false"
image:
  tag: 7690f8aa17b1a2829b4166897fab3c7e0696d020
