replicaCount: 1
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
env:
  STREAMLIT_SERVER_GATHER_USAGE_STATS: "false"
image:
  tag: 5bf9e8c85a01118621c66be6bb9a81015a211c2d
