replicaCount: 1
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
env:
  STREAMLIT_SERVER_GATHER_USAGE_STATS: "false"
image:
  tag: 98f4bd05b9eaa89343a7306cf5b8368803b69fdc
