deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
image:
  tag: 3fc79aa5417087ffe557fe63fb277b47d15a96ef
