deployment:
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
replicaCount: 3
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
image:
  tag: 22e66f55865e405a784d3c596cd1b05d95ed4c89
